### ISSUE TITLE
Failed rmdir

### ISSUE THREAD

**Issue by aflaxman** [p-b-j/census-das-container#3] opened 2021-02-10 00:59 UTC
```
2021-02-09 16:46:01,720 e2e_1940_reader.py:313 (make_block_node) creating geocode: 4902100140
The protected relative total L1 error is 0.07 (above 0.07 with 90% confidence)
Traceback (most recent call last):
  File "/ihme/homes/abie/projects/2021/census-das-container/census2020-das-e2e/das_framework/driver.py", line 757, in <module>
    main()
  File "/ihme/homes/abie/projects/2021/census-das-container/census2020-das-e2e/das_framework/driver.py", line 742, in main
    raise(e)
  File "/ihme/homes/abie/projects/2021/census-das-container/census2020-das-e2e/das_framework/driver.py", line 739, in main
    data = das.run()
  File "/ihme/homes/abie/projects/2021/census-das-container/census2020-das-e2e/das_framework/driver.py", line 615, in run
    valid = self.runValidator(original_data, written_data)
  File "/ihme/homes/abie/projects/2021/census-das-container/census2020-das-e2e/das_framework/driver.py", line 574, in runValidator
    valid = self.validator.validate(original_data, written_data)
  File "/tmp/das_decennial1274108.zip/programs/validator.py", line 59, in validate
  File "/tmp/das_decennial1274108.zip/programs/validator.py", line 257, in make_certificate
  File "/tmp/das_decennial1274108.zip/das_framework/certificate_printer/certificate.py", line 139, in typeset
  File "/usr/local/anaconda3/lib/python3.6/shutil.py", line 484, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/local/anaconda3/lib/python3.6/shutil.py", line 482, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/tmplpkp8hw3'
(base) [abie@long-uge-archive-p145 census-das-container]$
```

**Comment by p-b-j** [comment] 2021-02-10 02:25
I'll investigate this further tonight to see if I can reproduce the issue.

Out of curiosity, what output do you get by running `$ ls ~/das_files/output`? I think the step that failed is related to generating a certificate (at the end of the run), but I'm still trying to learn how everything fits together so I might be wrong here.

**Comment by aflaxman** [comment] 2021-02-10 03:42
(base) [abie@long-uge-archive-p145 2021]$ ls -halt ~/das_files/output
total 44K
drwxr-xr-x 2 abie Domain Users 102K Feb  9 16:44 MDF_PER.txt
drwxr-xr-x 2 abie Domain Users 102K Feb  9 16:42 MDF_UNIT.txt

**Comment by p-b-j** [comment] 2021-02-10 18:24
Ok so couple of notes:
1. It looks like your DAS run failed on the very last step (creating the certificate), so the `MDF_PER.txt` and `MDF_UNIT.txt` directories I think have complete results, they just need to be combined. I think running the following should work:
```bash
$ cd census2020-das-e2e
$ python3 s3cat.py ~/das_files/output/MDF_PER.txt/ --demand_success
$ python3 s3cat.py ~/das_files/output/MDF_UNIT.txt/ --demand_success
# Should now see two new files, MDF_PER.dat and MDF_UNIT.dat
$ ls ~/das_files/output/
# Can check the number of records in each file
# For MDF_PER.dat I get 132404766 records
$ head -n 3 ~/das_files/output/MDF_PER.dat
# For MDF_UNIT.dat I get 38492963 records
$ head -n 3 ~/das_files/output/MDF_UNIT.dat
```
2. The rmdir error actually looks like a bug in how `shutil.rmtree` plays with some file systems. [This thread](https://github.com/hashdist/hashdist/issues/113) has a similar discussion. I'll change the code to use an alternative and try to test it tonight, hopefully having something tomorrow that you can attempt a rerun with!

**Comment by aflaxman** [comment] 2021-02-10 19:20
Confirmed that running the suggested steps works, and yields MDF_PER and UNIT with expected number of rows!

**Comment by p-b-j** [comment] 2021-02-11 20:18
Awesome glad to hear it! I just pushed a fix to the certificate generation to use `rm -rf` instead of `shutil.rmtree` which I think should fix the original `rmdir` issue. When you get a chance to do another run it'd be awesome to know if it can get all the way through without errors now!

**Comment by aflaxman** [comment] 2021-02-11 23:36
Success!

  adding: ihme/homes/abie/das_files/output/MDF_PER.dat (deflated 95%)
  adding: ihme/homes/abie/das_files/output/MDF_UNIT.dat (deflated 91%)
DAS done at Thu Feb 11 14:31:31 PST 2021

**Comment by p-b-j** [comment] 2021-02-11 23:48
Nice! Closing this issue for now

**Closed by p-b-j** 2021-02-11 23:48 UTC
